### ISSUE TITLE
Make base url changable so project can be used for Binance-us?

### ISSUE THREAD

**Issue by bl4ze** [Ashlar/binance-api-node#307] opened 2020-12-29 10:22 UTC
Hey, I think Binance-us has the same API as Binance.
Is it possible for the base url to be passed outside instead of being hardcoded?

**Comment by jorisw** [comment] 2021-01-31 08:39
Dupe of #297 . 

Would be fixed by #278 and/or #283 .

**Closed** 2021-01-31 17:44 UTC
